Elaborado por Daphne Sofia Gonzalez Cano
Parte 3 del 3er examen parcial

In [16]:
from math import sqrt
import numpy as np

In [17]:
class KNNClassifier:
    def __init__(self, k):
        self.k = k
        self.data_train = None
        self.label_train = None

    def fit(self, data_train, label_train):
        self.data_train = data_train
        self.label_train = label_train

    def euclidean_distance(self, x1, x2):
        squared_diff_sum = 0
        for i in range(len(x1)):
            squared_diff_sum += (x1[i] - x2[i]) ** 2
        return sqrt(squared_diff_sum)

    def get_neighbors(self, x):
        distances = []
        for i in range(len(self.data_train)):
            distance = self.euclidean_distance(x, self.data_train[i])
            distances.append((distance, self.label_train[i]))

        #for d in range(len(distances)):
           #print(distances[d][0])
        
        #ordenamiento
        for i in range(len(distances)):
            min_idx = i
            for j in range(i + 1, len(distances)):
                if distances[j][0] < distances[min_idx][0]:
                    min_idx = j
            distances[i], distances[min_idx] = distances[min_idx], distances[i]

        k_nearest_neighbors = distances[:self.k]
            
        return k_nearest_neighbors


    def predict(self, data_train):
        y_pred = []
        k = 0
        for data_train in data_train:
            k = k+1
            neighbors = self.get_neighbors(data_train)
            prom = 0 
            for d in range(len(neighbors)):
                prom = prom + neighbors[d][1]
            prom = int(prom / len(neighbors))
            y_pred.append(prom)

        return y_pred


In [18]:
def getNPmatrix(archive):
    with open(archive, 'r') as file:
        lines = file.readlines()
        
    data = [line.strip().split(',') for line in lines]

    return np.array(data, dtype=float)

data = getNPmatrix('irism.data')
print(data.shape)

dataTrain = data[:90, :4]
label_train = data[:90, 4]
print(dataTrain.shape)
print(label_train.shape)

dataTest = data[90:150, :4]
label_test = data[90:150, 4]
print(dataTest.shape)
print(label_test.shape)

(150, 5)
(90, 4)
(90,)
(60, 4)
(60,)


In [19]:
def knnAlgorithm(data_train, label_train, X_test, Y_test, k):
    clases = np.unique(label_train)
    confussionMatrix = np.zeros((len(clases),len(clases)), dtype=int)
    knn = KNNClassifier(k)
    knn.fit(data_train, label_train)
    predictions = knn.predict(X_test)
    for i in range (len(predictions)):
        confussionMatrix[int(predictions[i])-1][int(Y_test[i])-1] += 1
    accuracy = np.trace(confussionMatrix)/np.sum(confussionMatrix)
    #se imprime matriz de confusion
    print("the accuracy with k = ",k, " is ",accuracy*100, "%")
    print(confussionMatrix, "\n")
    #return accuracy

In [20]:
knnAlgorithm(dataTrain, label_train, dataTest, label_test, 3)
knnAlgorithm(dataTrain, label_train, dataTest, label_test, 5)


the accuracy with k =  3  is  93.33333333333333 %
[[20  0  0]
 [ 0 20  4]
 [ 0  0 16]] 

the accuracy with k =  5  is  90.0 %
[[20  0  0]
 [ 0 20  6]
 [ 0  0 14]] 

