Elaborado por Daphne Sofia Gonzalez Cano
Parte 2 del 3er examen parcial

In [1]:
from math import sqrt
import numpy as np

In [2]:
def getNPmatrix(archive):
    with open(archive, 'r') as file:
        lines = file.readlines()
        
    data = [line.strip().split(',') for line in lines]

    return np.array(data, dtype=float)

data = getNPmatrix('irism.data')
print(data.shape)

dataTrain = data[:90, :4]
label_train = data[:90, 4]
print(dataTrain.shape)
print(label_train.shape)

dataTest = data[90:150, :4]
label_test = data[90:150, 4]
print(dataTest.shape)
print(label_test.shape)

(150, 5)
(90, 4)
(90,)
(60, 4)
(60,)


In [3]:
def promLabel(label, data):
    dataprom = np.zeros_like(data[0, :])
    cont = 0 
    for i in range (data.shape[0]):
        if data[i][4] == label:
           dataprom[0] = dataprom[1] + data[i][0]
           dataprom[1] = dataprom[1] + data[i][1]
           dataprom[2] = dataprom[2] + data[i][2]
           dataprom[3] = dataprom[3] + data[i][3]
           dataprom[4] = dataprom[4] + data[i][4]
           cont =cont + 1
    return (dataprom/cont)

prom1 = promLabel(1, data)   
prom2 = promLabel(2, data)
prom3 = promLabel(3, data)      
print(prom1, prom2, prom3)

[3.454 3.418 1.464 0.244 1.   ] [2.828 2.77  4.26  1.326 2.   ] [3.032 2.974 5.552 2.026 3.   ]


In [4]:
class KNNClassifier:
    def __init__(self):
        self.data_train = None
        self.label_train = None

    def fit(self, data_train, label_train):
        self.data_train = data_train
        self.label_train = label_train

    def euclidean_distance(self, x1, x2):
        squared_diff_sum = 0
        for i in range(len(x1)):
            squared_diff_sum += (x1[i] - x2[i]) ** 2
        return sqrt(squared_diff_sum)
    
    def newget_neighbors(self, x):
        distances = []
        for i in range(1,3):
            distance = self.euclidean_distance(x, promLabel(i, data))
            distances.append((distance, i)) 
        
        for i in range(len(distances)):
            min_idx = i
            for j in range(i + 1, len(distances)):
                if distances[j][0] < distances[min_idx][0]:
                    min_idx = j
            distances[i], distances[min_idx] = distances[min_idx], distances[i]
            
        return distances

    def predict(self, data_train):
        y_pred = []
        k = 0
        for data_train in data_train:
            k = k+1
            neighbors = self.newget_neighbors(data_train)
            y_pred.append(neighbors[0][1])
        return y_pred



In [5]:
def knnAlgorithm(data_train, label_train, X_test, Y_test):
    clases = np.unique(label_train)
    confussionMatrix = np.zeros((len(clases),len(clases)), dtype=int)
    knn = KNNClassifier()
    knn.fit(data_train, label_train)
    predictions = knn.predict(X_test)
    for i in range (len(predictions)):
        confussionMatrix[int(predictions[i])-1][int(Y_test[i])-1] += 1
    accuracy = np.trace(confussionMatrix)/np.sum(confussionMatrix)
    #se imprime matriz de confusion
    print("the accuracy is ",accuracy*100, "%")
    print(confussionMatrix, "\n")
    #return accuracy

In [6]:
knnAlgorithm(dataTrain, label_train, dataTest, label_test)


the accuracy is  65.0 %
[[20  1  0]
 [ 0 19 20]
 [ 0  0  0]] 

