In [5]:
import numpy as np

with open('optdigits.tra', 'r') as archivo:
    contenido = archivo.read()

lineas = contenido.split('\n')
elementos = []
for linea in lineas:
    elementos.extend(linea.split(','))

arreglo = np.array([int(elemento) for elemento in elementos if elemento.strip()])

print(arreglo.shape)



FileNotFoundError: [Errno 2] No such file or directory: 'optdigits.tra'

In [17]:
import numpy as np

# Lee el archivo de texto
with open('optdigits.tes', 'r') as file:
    lines = file.readlines()

# Elimina los caracteres de salto de línea y divide los valores por comas
data = [line.strip().split(',') for line in lines]

# Convierte la lista en una matriz de numpy
np_array = np.array(data, dtype=int)

print(np_array.shape)

subset_array = np_array[:, :64]
print(subset_array.shape)
print(subset_array)


subset_array2 = np_array[:, 64]
print(subset_array2.shape)
print(subset_array2)
# Imprime el subset_array



(1797, 65)
(1797, 64)
[[ 0  0  5 ...  0  0  0]
 [ 0  0  0 ... 10  0  0]
 [ 0  0  0 ... 16  9  0]
 ...
 [ 0  0  1 ...  6  0  0]
 [ 0  0  2 ... 12  0  0]
 [ 0  0 10 ... 12  1  0]]
(1797,)
[0 1 2 ... 8 9 8]


In [ ]:
import numpy as np

# Lee el archivo de texto
with open('archivo.txt', 'r') as file:
    lines = file.readlines()

# Elimina los caracteres de salto de línea y divide los valores por comas
data = [line.strip().split(',')[:64] for line in lines]

# Convierte la lista en una matriz de numpy
np_array = np.array(data, dtype=int)


In [ ]:
# Función para calcular la distancia euclidiana entre dos puntos
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

# Clase del clasificador K-NN
class KNNClassifier:
    def __init__(self, k):
        self.k = k

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        y_pred = []
        for i in range(len(X_test)):
            distances = []
            for j in range(len(self.X_train)):
                dist = euclidean_distance(X_test[i], self.X_train[j])
                distances.append((dist, self.y_train[j]))
            distances.sort(key=lambda x: x[0])  # Ordenar distancias de menor a mayor
            neighbors = distances[:self.k]  # Obtener los k vecinos más cercanos
            classes = [neighbor[1] for neighbor in neighbors]  # Obtener las clases de los vecinos
            y_pred.append(max(set(classes), key=classes.count))  # Clasificación por voto mayoritario
        return y_pred

# Ejemplo de uso
X_train = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(X_train.shape)
y_train = np.array([0, 1, 1, 0])
print(y_train.shape)
X_test = np.array([[2, 3, 4], [5, 6, 7]])

knn = KNNClassifier(k=3)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)

print(predictions)